/**
 * SEGUIMIENTO_ANEMIA_GESTANTE - Sistema de Seguimiento de Salud
 * Registros: 32 | Generado: 2026-03-17
 */

export const SEGUIMIENTO_ANEMIA_GESTANTE = [
  {
    "n": 1,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 60622583,
    "HC": 17008,
    "Nombres_P": "BALTAZAR CHUMACERO JENNY",
    "FECHA_NAC": "27/03/2008",
    "Edad": 17,
    "Gen": "F",
    "Domicilio": "CASERIO DE LA LAGUNA",
    "DIAGNOSTICO": "17/01/2026",
    "ATENDIO_DIAGNOSTICO": "SILVA CARDENAS DANY MARIA",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "17/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 11.6,
    "ATENDIO_TTO_1": "ZAPATA ANCAJIMA YURY DE LOS MILAGROS",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 2,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 74326638,
    "HC": 14727,
    "Nombres_P": "CARRILLO HUACHES FLORISELDA",
    "FECHA_NAC": "18/07/1996",
    "Edad": 29,
    "Gen": "F",
    "Domicilio": "CUMBICUS ALTO",
    "DIAGNOSTICO": "13/01/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.8,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 3,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 49015345,
    "HC": 16912,
    "Nombres_P": "C�RDOVA GARC-A GLADYS",
    "FECHA_NAC": "31/08/2001",
    "Edad": 24,
    "Gen": "F",
    "Domicilio": "LUCUMO",
    "DIAGNOSTICO": "30/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13.2,
    "TTO_1": "28/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 12,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 4,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 48245394,
    "HC": 48245394,
    "Nombres_P": "CHAVEZ HUAMAN ARACELLY",
    "FECHA_NAC": "01/10/1990",
    "Edad": 35,
    "Gen": "F",
    "Domicilio": "",
    "DIAGNOSTICO": "16/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13.3,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 5,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 72714662,
    "HC": 17093,
    "Nombres_P": "CHUMACERO BERRU ROSARIO",
    "FECHA_NAC": "29/07/1999",
    "Edad": 26,
    "Gen": "F",
    "Domicilio": "CHANGRA",
    "DIAGNOSTICO": "03/01/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.3,
    "TTO_1": "03/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 12,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 6,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 76966920,
    "HC": 14708,
    "Nombres_P": "CORDOVA GARCIA FLORELISA",
    "FECHA_NAC": "07/07/2003",
    "Edad": 22,
    "Gen": "F",
    "Domicilio": "CASERIO DE LUCUMO",
    "DIAGNOSTICO": "16/02/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 7,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 48587449,
    "HC": 8620,
    "Nombres_P": "GARCIA CORDOVA ANDREA",
    "FECHA_NAC": "15/12/1993",
    "Edad": 32,
    "Gen": "F",
    "Domicilio": "TINGOS",
    "DIAGNOSTICO": "15/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13,
    "TTO_1": "15/02/2026",
    "TIPO_TTO_1": "PR",
    "DOSAJE_1B": 14,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 8,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 74858526,
    "HC": 17170,
    "Nombres_P": "GARCIA MONTALVAN SOILIDEINE",
    "FECHA_NAC": "10/02/2005",
    "Edad": 21,
    "Gen": "F",
    "Domicilio": "CASERIO DE TINGOS HUACA",
    "DIAGNOSTICO": "24/01/2026",
    "ATENDIO_DIAGNOSTICO": "SILVA CARDENAS DANY MARIA",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "14/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 0,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 9,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 60557282,
    "HC": 17129,
    "Nombres_P": "GARCIA MORETO LUZ MARIA",
    "FECHA_NAC": "21/08/2007",
    "Edad": 18,
    "Gen": "F",
    "Domicilio": "CASERIO DE CHANGRA",
    "DIAGNOSTICO": "02/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13,
    "TTO_1": "02/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 13,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "06/02/2026",
    "TIPO_TTO_2": "LEV",
    "DOSAJE_2": 0,
    "ATENDIO_TTO_2": "VERGARA ROJAS JEMMY ALIDA",
    "TTO_3": "02/03/2026",
    "TIPO_TTO_3": "PR",
    "DOSAJE_2B": 12.8,
    "ATENDIO_TTO_3": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 10,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 73578049,
    "HC": 14787,
    "Nombres_P": "JIMENEZ CHUMACERO YANET",
    "FECHA_NAC": "15/12/1995",
    "Edad": 30,
    "Gen": "F",
    "Domicilio": "PAPELILLO",
    "DIAGNOSTICO": "27/01/2026",
    "ATENDIO_DIAGNOSTICO": "VERGARA ROJAS JEMMY ALIDA",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "27/01/2026",
    "TIPO_TTO_1": "MOD",
    "DOSAJE_1B": 11.9,
    "ATENDIO_TTO_1": "ANTON CHECA JUSTO JEFFERSON",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 11,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 45825525,
    "HC": 9836,
    "Nombres_P": "JIMENEZ ROMAN ISMELDA",
    "FECHA_NAC": "28/09/1988",
    "Edad": 37,
    "Gen": "F",
    "Domicilio": "CASERIO DE TASAJERAS",
    "DIAGNOSTICO": "01/01/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.6,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 12,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 60701602,
    "HC": 5140,
    "Nombres_P": "MORETO GARCIA MARIBEL",
    "FECHA_NAC": "14/11/1999",
    "Edad": 26,
    "Gen": "F",
    "Domicilio": "CHANGRA",
    "DIAGNOSTICO": "06/02/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12,
    "TTO_1": "06/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 0,
    "ATENDIO_TTO_1": "VERGARA ROJAS JEMMY ALIDA",
    "TTO_2": "06/03/2026",
    "TIPO_TTO_2": "LEV",
    "DOSAJE_2": 12.6,
    "ATENDIO_TTO_2": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 13,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 60557293,
    "HC": 17109,
    "Nombres_P": "MORETO HUAMAN FIORELA",
    "FECHA_NAC": "17/08/2007",
    "Edad": 18,
    "Gen": "F",
    "Domicilio": "SAN FRANCISCO",
    "DIAGNOSTICO": "17/02/2026",
    "ATENDIO_DIAGNOSTICO": "ANTON CHECA JUSTO JEFFERSON",
    "TIPO_ANEMIA": "MODERADA",
    "DOSAJE_1": 9.3,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 14,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 44271329,
    "HC": 6392,
    "Nombres_P": "PE�A NU�EZ REYDELINDA",
    "FECHA_NAC": "01/01/1983",
    "Edad": 43,
    "Gen": "F",
    "Domicilio": "CHANGRA",
    "DIAGNOSTICO": "22/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12,
    "TTO_1": "22/02/2026",
    "TIPO_TTO_1": "PR",
    "DOSAJE_1B": 14,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 15,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 75530311,
    "HC": 14661,
    "Nombres_P": "PE�A QUISPE NICOL LISBETH",
    "FECHA_NAC": "04/05/2003",
    "Edad": 22,
    "Gen": "F",
    "Domicilio": "CASER-O DE VILCAS",
    "DIAGNOSTICO": "02/01/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 16,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 44625144,
    "HC": 8318,
    "Nombres_P": "PE�A ROMAN CENEIDA",
    "FECHA_NAC": "27/03/1987",
    "Edad": 38,
    "Gen": "F",
    "Domicilio": "TINGOS",
    "DIAGNOSTICO": "23/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12,
    "TTO_1": "23/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 12,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 17,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 70975518,
    "HC": 70975518,
    "Nombres_P": "ROBLEDO ABAD MARIA NORELIA",
    "FECHA_NAC": "28/08/2002",
    "Edad": 23,
    "Gen": "F",
    "Domicilio": "COMUNID. CUJACA SECTOR RODEOPAMPA S/N",
    "DIAGNOSTICO": "29/01/2026",
    "ATENDIO_DIAGNOSTICO": "PATI�O VALLE KARLA JENIFER",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12,
    "TTO_1": "28/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 11.6,
    "ATENDIO_TTO_1": "ANTON CHECA JUSTO JEFFERSON",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 18,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 74739400,
    "HC": 12065,
    "Nombres_P": "ROMAN MONTALVAN ERMANDINA",
    "FECHA_NAC": "12/09/1995",
    "Edad": 30,
    "Gen": "F",
    "Domicilio": "LA COFRADIA",
    "DIAGNOSTICO": "09/01/2026",
    "ATENDIO_DIAGNOSTICO": "DIAZ DIAZ ANGIE CARMELINA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13.5,
    "TTO_1": "09/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 13,
    "ATENDIO_TTO_1": "DIAZ DIAZ ANGIE CARMELINA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 19,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 61922877,
    "HC": 8559,
    "Nombres_P": "RUIZ GARCIA MARIA ESPERANZA",
    "FECHA_NAC": "25/09/2009",
    "Edad": 16,
    "Gen": "F",
    "Domicilio": "MALACHE",
    "DIAGNOSTICO": "08/01/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.4,
    "TTO_1": "09/02/2026",
    "TIPO_TTO_1": "PR",
    "DOSAJE_1B": 12.5,
    "ATENDIO_TTO_1": "QUEREVALU REFORME FIORELLA YADIRA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 20,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 43939961,
    "HC": 6915,
    "Nombres_P": "VELASQUEZ CARHUAPOMA EUMELIA",
    "FECHA_NAC": "23/07/1982",
    "Edad": 43,
    "Gen": "F",
    "Domicilio": "PACAIPAMPA",
    "DIAGNOSTICO": "10/02/2026",
    "ATENDIO_DIAGNOSTICO": "AGUILAR LEON LESLY ISABEL",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.3,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 21,
    "IPRESS_HIS": "E.S.  PACAIPAMPA",
    "N_DNI_HIS": 70368589,
    "HC": 17033,
    "Nombres_P": "VELASQUEZ SALVADOR LESVY",
    "FECHA_NAC": "08/12/1998",
    "Edad": 27,
    "Gen": "F",
    "Domicilio": "PACAIPAMPA",
    "DIAGNOSTICO": "04/01/2026",
    "ATENDIO_DIAGNOSTICO": "ANTON CHECA JUSTO JEFFERSON",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "03/02/2026",
    "TIPO_TTO_1": "PR",
    "DOSAJE_1B": 13,
    "ATENDIO_TTO_1": "ANTON CHECA JUSTO JEFFERSON",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 22,
    "IPRESS_HIS": "P.S CUMBICUS",
    "N_DNI_HIS": 72360597,
    "HC": 3144,
    "Nombres_P": "HUAMAN HUAMAN FLOR",
    "FECHA_NAC": "25/03/1997",
    "Edad": 28,
    "Gen": "F",
    "Domicilio": "CUMBICUS",
    "DIAGNOSTICO": "22/01/2026",
    "ATENDIO_DIAGNOSTICO": "JUAREZ ACARO ROSANGELICA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13.9,
    "TTO_1": "20/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 13.9,
    "ATENDIO_TTO_1": "JUAREZ ACARO ROSANGELICA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 23,
    "IPRESS_HIS": "P.S EL PUERTO",
    "N_DNI_HIS": 76876844,
    "HC": 76876844,
    "Nombres_P": "DELGADO BARCO HILDA IDA",
    "FECHA_NAC": "08/10/1998",
    "Edad": 27,
    "Gen": "F",
    "Domicilio": "NUEVA ALIANZA",
    "DIAGNOSTICO": "26/01/2026",
    "ATENDIO_DIAGNOSTICO": "RODRIGUEZ CARDENAS BROOKE MARJORIE",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 16.2,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 24,
    "IPRESS_HIS": "P.S EL PUERTO",
    "N_DNI_HIS": 73569718,
    "HC": 3049,
    "Nombres_P": "GARCIA GARCIA SANDI BELL",
    "FECHA_NAC": "12/02/2003",
    "Edad": 23,
    "Gen": "F",
    "Domicilio": "SAN JUAN",
    "DIAGNOSTICO": "23/01/2026",
    "ATENDIO_DIAGNOSTICO": "RODRIGUEZ CARDENAS BROOKE MARJORIE",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 13.1,
    "TTO_1": "23/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 13.5,
    "ATENDIO_TTO_1": "CALVA ORDINOLA DINORA LISBETH",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 25,
    "IPRESS_HIS": "P.S EL PUERTO",
    "N_DNI_HIS": 46518719,
    "HC": 649,
    "Nombres_P": "MORALES CHANTA AURE MARIELA",
    "FECHA_NAC": "14/03/1986",
    "Edad": 39,
    "Gen": "F",
    "Domicilio": "CASERIO DE ARANZA",
    "DIAGNOSTICO": "27/01/2026",
    "ATENDIO_DIAGNOSTICO": "RODRIGUEZ CARDENAS BROOKE MARJORIE",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.8,
    "TTO_1": "27/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 0,
    "ATENDIO_TTO_1": "CALVA ORDINOLA DINORA LISBETH",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 26,
    "IPRESS_HIS": "P.S EL PUERTO",
    "N_DNI_HIS": 61577772,
    "HC": 3045,
    "Nombres_P": "ROMAN FLORES BLANCA FLOR",
    "FECHA_NAC": "03/08/2008",
    "Edad": 17,
    "Gen": "F",
    "Domicilio": "PAREDONES",
    "DIAGNOSTICO": "24/01/2026",
    "ATENDIO_DIAGNOSTICO": "RODRIGUEZ CARDENAS BROOKE MARJORIE",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.4,
    "TTO_1": "24/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 12.5,
    "ATENDIO_TTO_1": "CALVA ORDINOLA DINORA LISBETH",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 27,
    "IPRESS_HIS": "P.S.  LAGUNAS DE SAN PABLO",
    "N_DNI_HIS": 76786454,
    "HC": 380,
    "Nombres_P": "CHUQUIHUANGA ZURITA SARAI",
    "FECHA_NAC": "25/11/2004",
    "Edad": 21,
    "Gen": "F",
    "Domicilio": "CASERIO DE LIVIN DE CURILCAS",
    "DIAGNOSTICO": "23/02/2026",
    "ATENDIO_DIAGNOSTICO": "CHUQUILLANQUI RUIZ FERNANDA MARIA SOLEDAD",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 11,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 28,
    "IPRESS_HIS": "P.S.  LAGUNAS DE SAN PABLO",
    "N_DNI_HIS": 61618489,
    "HC": 837,
    "Nombres_P": "CRUZ JIMENEZ ROSALIA",
    "FECHA_NAC": "04/07/2009",
    "Edad": 16,
    "Gen": "F",
    "Domicilio": "CASER-O MARAY DE LAGUNAS DE SAN PABLO",
    "DIAGNOSTICO": "08/01/2026",
    "ATENDIO_DIAGNOSTICO": "CASTILLO CAUCHA LUDUVINDA",
    "TIPO_ANEMIA": "SEVERA",
    "DOSAJE_1": 0,
    "TTO_1": "07/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 0,
    "ATENDIO_TTO_1": "CASTILLO CAUCHA LUDUVINDA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 29,
    "IPRESS_HIS": "P.S.  LAGUNAS DE SAN PABLO",
    "N_DNI_HIS": 76656751,
    "HC": 1639,
    "Nombres_P": "JIMENEZ FLORES MEDALI",
    "FECHA_NAC": "10/07/2003",
    "Edad": 22,
    "Gen": "F",
    "Domicilio": "CASER-O DE SAN LAZARO",
    "DIAGNOSTICO": "28/02/2026",
    "ATENDIO_DIAGNOSTICO": "CASTILLO CAUCHA LUDUVINDA",
    "TIPO_ANEMIA": "MODERADA",
    "DOSAJE_1": 9.3,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 30,
    "IPRESS_HIS": "P.S.  LAGUNAS DE SAN PABLO",
    "N_DNI_HIS": 74276379,
    "HC": 66,
    "Nombres_P": "JIMENEZ HERRERA LEYDA JOFANI",
    "FECHA_NAC": "10/02/2005",
    "Edad": 21,
    "Gen": "F",
    "Domicilio": "CASER-O DE LAGUNAS DE SAN PABLO",
    "DIAGNOSTICO": "29/01/2026",
    "ATENDIO_DIAGNOSTICO": "CASTILLO CAUCHA LUDUVINDA",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12,
    "TTO_1": "28/02/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 0,
    "ATENDIO_TTO_1": "CASTILLO CAUCHA LUDUVINDA",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 31,
    "IPRESS_HIS": "P.S.  LAGUNAS DE SAN PABLO",
    "N_DNI_HIS": 74436402,
    "HC": 1463,
    "Nombres_P": "SUAREZ GARCIA LUZ ITALA",
    "FECHA_NAC": "26/04/2003",
    "Edad": 22,
    "Gen": "F",
    "Domicilio": "CASER-O DE LAGUNAS DE SAN PABLO",
    "DIAGNOSTICO": "13/02/2026",
    "ATENDIO_DIAGNOSTICO": "CASTILLO CAUCHA LUDUVINDA",
    "TIPO_ANEMIA": "MODERADA",
    "DOSAJE_1": 9.9,
    "TTO_1": "",
    "TIPO_TTO_1": "",
    "DOSAJE_1B": "",
    "ATENDIO_TTO_1": "",
    "TTO_2": "",
    "TIPO_TTO_2": "",
    "DOSAJE_2": "",
    "ATENDIO_TTO_2": "",
    "TTO_3": "",
    "TIPO_TTO_3": "",
    "DOSAJE_2B": "",
    "ATENDIO_TTO_3": "",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  },
  {
    "n": 32,
    "IPRESS_HIS": "P.S. CACHIACO",
    "N_DNI_HIS": 48923683,
    "HC": 261,
    "Nombres_P": "CAMPOS JULCA LUZ MARIA",
    "FECHA_NAC": "09/06/1994",
    "Edad": 31,
    "Gen": "F",
    "Domicilio": "CAS. MANGAS DE CACHIACO",
    "DIAGNOSTICO": "16/01/2026",
    "ATENDIO_DIAGNOSTICO": "TIMANA YOVERA LIZBET MEDALY",
    "TIPO_ANEMIA": "",
    "DOSAJE_1": 12.1,
    "TTO_1": "31/01/2026",
    "TIPO_TTO_1": "LEV",
    "DOSAJE_1B": 12.6,
    "ATENDIO_TTO_1": "RONDOY DIAZ DANIEL ARMANDO",
    "TTO_2": "31/01/2026",
    "TIPO_TTO_2": "",
    "DOSAJE_2": 12.6,
    "ATENDIO_TTO_2": "TIMANA YOVERA LIZBET MEDALY",
    "TTO_3": "15/02/2026",
    "TIPO_TTO_3": "PR",
    "DOSAJE_2B": 12.9,
    "ATENDIO_TTO_3": "TIMANA YOVERA LIZBET MEDALY",
    "TTO_4": "",
    "TIPO_TTO_4": "",
    "DOSAJE_3": "",
    "ATENDIO_TTO_4": "",
    "TTO_5": "",
    "TIPO_TTO_5": "",
    "ATENDIO_TTO_5": "",
    "TTO_6": "",
    "TIPO_TTO_6": "",
    "ATENDIO_TTO_6": "",
    "T�rmino_Act": "",
    "ATENDIO_T�rmino_Act": "",
    "Recuperado": "",
    "DOSAJE_4": "",
    "ATENDIO_Recuperado": ""
  }
];